# Header
menu:
  Home: /
  Archives: /archives
  #Tags: /tags
  #Categories: /categories
  Github:
    url: https://github.com/jsonbruce
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Maxthread

# URL of the Home page image
index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/jsonbruce
facebook_url: https://facebook.com/jsonbruce
github_url: https://github.com/jsonbruce
linkedin_url: https://linkedin.com/in/xuhuan
mailto: xuhuan@live.cn
